require 'time'
require 'date'
require 'volt/helpers/time/volt_time'
require 'volt/helpers/time/local_volt_time' if RUBY_PLATFORM == 'opal'
require 'volt/helpers/time/calculations'
require 'volt/helpers/time/local_calculations' if RUBY_PLATFORM == 'opal'
require 'volt/helpers/time/duration'
require 'volt/helpers/time/numeric'
