source 'https://rubygems.org'

gem 'volt', path: '/Users/ryanstout/Sites/volt/volt'


# The following gem's are optional for themeing

# Twitter bootstrap
gem 'volt-bootstrap'

# Simple theme for bootstrap, remove to theme yourself.
gem 'volt-bootstrap-jumbotron-theme'


gem 'volt-fields', path: '/Users/ryanstout/Sites/volt/apps/volt-fields'

# Server for MRI
platform :mri do
  gem 'thin', '~> 1.6.0'
  gem 'bson_ext'
end

# Server for jruby
platform :jruby do
  gem 'jubilee'
end

#---------------------
# Needed at the moment
gem 'opal', git: 'https://github.com/opal/opal.git'
gem 'opal-jquery', :git => 'https://github.com/opal/opal-jquery.git'
gem 'sockjs', git: 'https://github.com/kacperk/sockjs-ruby.git', require: false, platforms: :mri
