source 'https://rubygems.org'

gem 'volt', path: '../../../'

# The following gem's are optional for themeing

# Twitter bootstrap
gem 'volt-bootstrap'

# Simple theme for bootstrap, remove to theme yourself.
gem 'volt-bootstrap_jumbotron_theme'

gem 'volt-fields'
gem 'volt-user_templates'
gem 'volt-mongo', path: '/Users/ryanstout/Sites/volt/apps/volt-mongo'

gem 'opal'

gem 'concurrent-ruby-ext'

# Server for MRI
platform :mri do
  gem 'thin', '~> 1.6.0'
  gem 'bson_ext', '~> 1.9.0'
end

# Server for jruby
platform :jruby do
  gem 'jubilee'
end
